import { ProfessionalProfile } from '../types/professional';
import { Product } from '../types/product';
import { Booking } from '../types/booking';

export const MOCK_PROFESSIONALS: ProfessionalProfile[] = [
  {
    id: 'mohammad_thaha_hussain_2',
    userId: 'usr_thaha',
    name: 'Mohammad Thaha Hussain',
    title: 'Videographer • Photographer • Director',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400',
    bannerImage: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?q=80&w=1200',
    verified: true,
    rating: 5.0,
    reviewCount: 24,
    experienceYears: 6,
    ratePerDay: 20000,
    bio: 'Mohammad Thaha Hussain is a premier Videographer, Photographer, and Film Director specializing in cinematic wedding documentaries, high-end fashion campaigns, and commercial videos.',
    state: 'California',
    district: 'Los Angeles',
    city: 'Los Angeles, CA',
    locations: ['Los Angeles, CA', 'Mumbai', 'Dubai'],
    categories: ['Videographers', 'Photographers'],
    services: [
      { id: 'srv_thaha_1', title: 'Full Day Shoot', category: 'Photography', rate: 20000, unit: 'per day', description: 'Includes 8 hours full day cinema & photography coverage with 4K color grading.' },
      { id: 'srv_thaha_2', title: 'Commercial Campaign', category: 'Videography', rate: 45000, unit: 'per project', description: 'Complete commercial campaign production with dual 4K cinema cameras and lighting setup.' },
    ],
    portfolio: [
      'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=800',
      'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=800',
      'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=800',
    ],
    equipment: ['Sony FX3 Cinema Line', 'Sony FE 24-70mm f/2.8 GM II', 'DJI Ronin RS3 Pro Gimbal'],
    certifications: ['Camcrew Master Creator', 'Sony Alpha Ambassador'],
    reviews: [
      { id: 'rev_t1', clientName: 'Rhea Kapoor', rating: 5, date: 'August 2026', comment: 'Mohammad is a visionary director! The cinematic quality was breathtaking.' },
    ],
    weeklyAvailability: { Mon: true, Tue: true, Wed: true, Thu: true, Fri: true, Sat: true, Sun: false },
    blockedDates: ['2026-08-20'],
    views: 1420,
    totalEarnings: 380000,
  },
  {
    id: 'fathima_shirin',
    userId: 'usr_fathima',
    name: 'Fathima Shirin',
    title: 'Photographer & Sound Designer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400',
    bannerImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1200',
    verified: true,
    rating: 4.9,
    reviewCount: 18,
    experienceYears: 5,
    ratePerDay: 10000,
    bio: 'Fathima Shirin is a professional photographer and sound designer producing stunning portraits, fashion shoots, and ambient sound design.',
    state: 'Kerala',
    district: 'Kochi',
    city: 'Kochi',
    locations: ['Kochi', 'Mumbai', 'Bangalore'],
    categories: ['Photographers', 'Sound Designer'],
    services: [
      { id: 'srv_fs_1', title: 'Portrait & Fashion Package', category: 'Photography', rate: 10000, unit: 'per day', description: 'Full day portrait session with retouching.' },
    ],
    portfolio: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=800',
    ],
    equipment: ['Canon EOS R5', '50mm f/1.2 L Lens'],
    certifications: ['Camcrew Verified Creator'],
    reviews: [],
    weeklyAvailability: { Mon: true, Tue: true, Wed: true, Thu: true, Fri: true, Sat: true, Sun: false },
    blockedDates: [],
    views: 890,
    totalEarnings: 180000,
  },
  {
    id: 'jordan_rivera',
    userId: 'usr_jordan',
    name: 'Jordan rivera',
    title: 'Film Editor & Sound Designer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400',
    bannerImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200',
    verified: true,
    rating: 5.0,
    reviewCount: 32,
    experienceYears: 7,
    ratePerDay: 15000,
    bio: 'Jordan Rivera is a senior video editor and sound designer crafting commercials, music videos, and film post-production.',
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    locations: ['Mumbai', 'Delhi'],
    categories: ['Designers', 'Editors'],
    services: [
      { id: 'srv_jr_1', title: 'Commercial Video Editing', category: 'Editing', rate: 15000, unit: 'per day', description: 'Color grading, sound mix, and 4K delivery.' },
    ],
    portfolio: [
      'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=800',
    ],
    equipment: ['Apple Mac Studio M2 Ultra', 'DaVinci Resolve Studio'],
    certifications: ['Certified Post-Production Specialist'],
    reviews: [],
    weeklyAvailability: { Mon: true, Tue: true, Wed: true, Thu: true, Fri: true, Sat: false, Sun: false },
    blockedDates: [],
    views: 1200,
    totalEarnings: 310000,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prd_1',
    name: 'Sony FX3 Full-Frame Cinema Line Camera',
    brand: 'Sony',
    category: 'Camera Bodies',
    type: 'sale',
    price: 399990,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=600',
    description: 'Compact Full-Frame Cinema Camera featuring 12.1MP BSI Sensor, 4K 120p video recording, S-Cinetone color science, and active cooling fan for unlimited recording duration.',
    inStock: true,
    rating: 4.9,
  },
  {
    id: 'prd_2',
    name: 'Sony FE 24-70mm f/2.8 GM II Lens',
    brand: 'Sony',
    category: 'Lenses',
    type: 'rental',
    price: 199900,
    rentalPricePerDay: 2500,
    condition: 'Like New',
    image: 'https://images.unsplash.com/photo-1617005082133-548c4dd27f35?q=80&w=600',
    description: 'The standard zoom redefined. Extreme resolution and bokeh in a 22% lighter chassis. Four XD linear motors provide blistering autofocus.',
    inStock: true,
    rating: 4.9,
  },
  {
    id: 'prd_3',
    name: 'Aputure LS 600d Pro Daylight LED Light',
    brand: 'Aputure',
    category: 'Lighting',
    type: 'rental',
    price: 185000,
    rentalPricePerDay: 3200,
    condition: 'Good',
    image: 'https://images.unsplash.com/photo-1527011046414-4781f1f94f8c?q=80&w=600',
    description: '600W Daylight Point-Source LED, output equivalent to 1200W HMI. Weather-resistant design with wireless Sidus Link app control.',
    inStock: true,
    rating: 4.8,
  },
  {
    id: 'prd_4',
    name: 'DJI Ronin RS3 Pro Gimbal Stabilizer',
    brand: 'DJI',
    category: 'Drones & Gimbals',
    type: 'sale',
    price: 85990,
    condition: 'New',
    image: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?q=80&w=600',
    description: 'Automated axis locks, extended carbon fiber arms, LiDAR focusing compatibility, and 4.5kg tested payload capacity.',
    inStock: true,
    rating: 4.8,
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'BK-4092',
    professionalId: 'mohammad_thaha_hussain_2',
    professionalName: 'Mohammad Thaha Hussain',
    professionalAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400',
    professionalTitle: 'Videographer • Photographer • Director',
    customerId: 'usr_demo_123',
    customerName: 'Thaha Hussain',
    serviceTitle: 'Full Day Shoot',
    startDate: '2026-08-15',
    endDate: '2026-08-15',
    daysCount: 1,
    location: 'Mumbai, Maharashtra',
    status: 'confirmed',
    ratePerDay: 20000,
    totalAmount: 20000,
    createdAt: '2026-08-01',
  },
];
